repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: make-lint
        name: make lint
        entry: make lint
        language: system
        pass_filenames: false
      - id: make-test
        name: make test
        entry: make test
        language: system
        pass_filenames: false
      - id: make-typecheck
        name: make typecheck
        entry: make typecheck
        language: system
        pass_filenames: false
